import "./models/flashcard.dart";

var dummyFlashcards = [
  Flashcard(
    id: 'q1',
    question:
        'How much merging can a Merg8er Model do, if you do it 10 times a day?',
    answer: "It can merge 10 different things.",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'How much money doe1s it cost to implement some DCF?',
    answer: "One...million...dollars.",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favo7rite colour?',
    answer: "It is dark blue.",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'What are 1comps?',
    answer: "Complications",
    category: "Process",
    subcategory: "Comps",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'Is the LBO more like7 the DCF or more like the Merger Model?',
    answer:
        "Trick question, it's neither. It's more related to the schmerger model.",
    category: "Valuation",
    subcategory: "LBO",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your fa4vorite colour?',
    answer: "Red",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'What is the Merge7r Model?',
    answer: "It's a model that describes the process of merging things",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'What does DCF s1tand for?',
    answer: "Clearly it's the distribution of cake for freedom fighters",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favorit7e colour?',
    answer: "Magenta",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'Basic Comps Q1uestion',
    answer: "Complications",
    category: "Process",
    subcategory: "Comps",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q3',
    question: 'Advanced Valu9ation LBO question',
    answer: "Advanced LBO answer",
    category: "Valuation",
    subcategory: "LBO",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q4',
    question: 'General Basic 3Accounting question',
    answer: "Red",
    category: "Accounting",
    subcategory: "General",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q1',
    question: 'Intermediate Merge7r Model Question',
    answer: "Intermediate Merger Model Answer",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q3',
    question: 'Intermediate dcf 3question',
    answer: "Clearly it's the distribution of cake for freedom fighters",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q4',
    question: 'Advanced G6eneral question',
    answer: "Magenta",
    category: "Accounting",
    subcategory: "General",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q1',
    question:
        'How much merging can 1a Merger Model do, if you do it 10 times a day?',
    answer: "It can merge 10 different things.",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'How much money d8oes it cost to implement some DCF?',
    answer: "One...million...dollars.",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is2 your favorite colour?',
    answer: "It is dark blue.",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'What are5 comps?',
    answer: "Complications",
    category: "Process",
    subcategory: "Comps",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'Is the LBO more 1like the DCF or more like the Merger Model?',
    answer:
        "Trick question, it's neither. It's more related to the schmerger model.",
    category: "Valuation",
    subcategory: "LBO",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favor9ite colour?',
    answer: "Red",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'What is the Mer1ger Model?',
    answer: "It's a model that describes the process of merging things",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'What does DCF stan8d for?',
    answer: "Clearly it's the distribution of cake for freedom fighters",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your 1favorite colour?',
    answer: "Magenta",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'Basic Com8ps Question',
    answer: "Complications",
    category: "Process",
    subcategory: "Comps",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q3',
    question: 'Advance1d Valuation LBO question',
    answer: "Advanced LBO answer",
    category: "Valuation",
    subcategory: "LBO",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q4',
    question: 'General Basic8 Accounting question',
    answer: "Red",
    category: "Accounting",
    subcategory: "General",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q1',
    question: 'Intermediate 2Merger Model Question',
    answer: "Intermediate Merger Model Answer",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q3',
    question: 'Intermediat7e dcf question',
    answer: "Clearly it's the distribution of cake for freedom fighters",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q4',
    question: 'Advanced Gener1al question',
    answer: "Magenta",
    category: "Accounting",
    subcategory: "General",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q1',
    question:
        'How much merging can7 a Merger Model do, if you do it 10 times a day?',
    answer: "It can merge 10 different things.",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'How much money doe3s it cost to implement some DCF?',
    answer: "One...million...dollars.",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is you5r favorite colour?',
    answer: "It is dark blue.",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'What1 are comps?',
    answer: "Complications",
    category: "Process",
    subcategory: "Comps",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'Is the LBO more like1 the DCF or more like the Merger Model?',
    answer:
        "Trick question, it's neither. It's more related to the schmerger model.",
    category: "Valuation",
    subcategory: "LBO",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favorite co3lour?',
    answer: "Red",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'What is the Merger Mo3del?',
    answer: "It's a model that describes the process of merging things",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'What does DCF stand for?',
    answer: "Clearly it's the distribution of cake for freedom fighters5",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favorite colour?3',
    answer: "Magenta",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'Basic Comps Question2',
    answer: "Complications",
    category: "Process",
    subcategory: "Comps",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'Advanced Valuation LBO question2',
    answer: "Advanced LBO answer",
    category: "Valuation",
    subcategory: "LBO",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q4',
    question: 'General Basic Accounting question2',
    answer: "Red",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
  ),
  Flashcard(
    id: 'q1',
    question: 'Intermediate Merger Model Question2',
    answer: "Intermediate Merger Model Answer",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
  ),
  Flashcard(
    id: 'q3',
    question: 'Intermediate dcf question2',
    answer: "Clearly it's the distribution of cake for freedom fighters",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Basic",
  ),
  Flashcard(
    id: 'q4',
    question: 'Advanced General question2',
    answer: "Magenta",
    category: "Accounting",
    subcategory: "General",
    complexity: "Basic",
  ),
];
