import "./models/flashcard.dart";

var dummyFlashcards = [
  Flashcard(
    id: 'q1',
    question:
        'How much merging can a Merger Model do, if you do it 10 times a day?',
    answer: "It can merge 10 different things.",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q3',
    question: 'How much money does it cost to implement some DCF?',
    answer: "One...million...dollars.",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Basic",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favorite colour?',
    answer: "It is dark blue.",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q1',
    question: 'What are comps?',
    answer: "Complications",
    category: "Process",
    subcategory: "Comps",
    complexity: "Advanced",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q3',
    question: 'Is the LBO more like the DCF or more like the Merger Model?',
    answer:
        "Trick question, it's neither. It's more related to the schmerger model.",
    category: "Valuation",
    subcategory: "LBO",
    complexity: "Basic",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favorite colour?',
    answer: "Red",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q1',
    question: 'What is the Merger Model?',
    answer: "It's a model that describes the process of merging things",
    category: "Process",
    subcategory: "Merger Model",
    complexity: "Advanced",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q3',
    question: 'What does DCF stand for?',
    answer: "Clearly it's the distribution of cake for freedom fighters",
    category: "Valuation",
    subcategory: "DCF",
    complexity: "Basic",
    viewed: "Not viewed",
  ),
  Flashcard(
    id: 'q4',
    question: 'What is your favorite colour?',
    answer: "Magenta",
    category: "Accounting",
    subcategory: "General",
    complexity: "Intermediate",
    viewed: "Not viewed",
  ),
];
